services:
  db:
    image: postgres:16
    container_name: postgres-db
    environment:
      POSTGRES_DB: JDE
      POSTGRES_USER: root
      POSTGRES_PASSWORD: justdoeat
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis
    command: ["redis-server", "--appendonly", "yes"]  # 비번 미사용
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: main-server
    depends_on:
      - db
      - redis
    environment:
      SPRING_PROFILES_ACTIVE: pg
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/JDE
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: justdoeat

      REDIS_HOST: redis
      REDIS_PORT: 6379
      # REDIS_PASSWORD:  # (미사용이면 생략)

      # env.local에서 치환
      JWT_SECRET: ${JWT_SECRET}
      ACCESS_TOKEN_EXPIRATION_TIME: ${ACCESS_TOKEN_EXPIRATION_TIME}
      REFRESH_TOKEN_EXPIRATION_TIME: ${REFRESH_TOKEN_EXPIRATION_TIME}
    ports:
      - "8080:8080"

volumes:
  pgdata:
  redisdata:
